### ISSUE TITLE
No entity: weather.astroweather_LONGITUTE_LATITUDE

### ISSUE THREAD

**Issue by hpservertech** [mawinkler/astroweather-card#3]
Says to create a custom card with the below, however no device exists called entity: weather.astroweather_LONGITUTE_LATITUDE

Long & Lat are separate entities.  Believe the documentation needs to be updated most likely to use weather.astroweather_ds5ss6g7njg1

**Comment by mawinkler** [comment]
During the initial configuration of the integration, the weather entity is created with the above name. LONGITUDE and LATITUDE are replaced with the values you have configured for your location

**Comment by mawinkler** [comment]
resolved

**Comment by maxxer** [comment]
Sorry for "abusing" of an old issue, but I too don't understand what entity name I have to give. In the entities list, if I search for `weather.astrow` it won't find anything. Then whether I use `weather.astroweather_45.863400_9.382268` or `weather.astroweather_45863400_9382268` it still won't find the entity. I cannot figure out what I'm doing wrong, if anybody can help... Thank you

**Comment by mawinkler** [comment]
You did install the AstroWeather custom integration, or?

**Comment by maxxer** [comment]
> You did install the AstroWeather custom integration, or?

It seems so
![immagine](https://github.com/mawinkler/astroweather-card/assets/240201/ab7611db-4715-4361-bca3-bd581db66d61)

**Comment by mawinkler** [comment]
then you should have a weather.astroweather entity in your states list. Did you check this?

**Comment by maxxer** [comment]
I don't have it

![immagine](https://github.com/mawinkler/astroweather-card/assets/240201/0dbe85ad-3b71-4966-afbe-f1324a50b86b)

**Comment by mawinkler** [comment]
which version of home assistant are you running? You should be on 2023.9+.
Otherwise enable debug logging for astroweather please and post the logs

**Comment by maxxer** [comment]
2023.8.0 😓

**Comment by maxxer** [comment]
Upgraded and worked, thank you! Sorry for bugging

**Comment by mawinkler** [comment]
🎉
